[server]
listen = ":8080"
public_base_url = "http://localhost:8080"
log_level = "debug"

[storage]
path = "../data"
max_age = "720h"
gc_interval = "1h"
stale_temp_age = "1h"

[repository.npm]
type = "npm"
path = "/npm/"
upstream = "https://registry.npmjs.org"
ttl = "24h"
forward_authorization = false

[repository.oci]
type = "oci"
path = "/v2/"
upstream = "https://registry-1.docker.io"
ttl = "1h"

[repository.pypi]
type = "pypi"
path = "/pypi/simple/"
upstream = "https://pypi.org/simple"
ttl = "24h"
allowed_file_origins = "https://files.pythonhosted.org"
forward_authorization = false
# publish_token_file = "../secrets/pypi-publish-token"
